### ISSUE TITLE
Oi tod

### ISSUE THREAD

**Issue by Len-cmd** [Felix-403/duo-canvas#1]
![IMG_20211226_164853_762](https://user-images.githubusercontent.com/84387230/147404711-10c319ef-a90a-4fd8-96be-4b71b0931d05.jpg)

Lu bikin project kok g ngajak2 sih njir 

> @Felix-403
> @Lingz-ui

**Comment by Felix-403** [comment]
> ![IMG_20211226_164853_762](https://user-images.githubusercontent.com/84387230/147404711-10c319ef-a90a-4fd8-96be-4b71b0931d05.jpg)
> 
> Lu bikin project kok g ngajak2 sih njir
> 
> > @Felix-403
> > @Lingz-ui

Sorry bang lu off jadi gua kirain lu mati 😁😁

**Comment by Felix-403** [comment]
Dah gua add lu

**Comment by Lingz-ui** [comment]
> ![IMG_20211226_164853_762](https://user-images.githubusercontent.com/84387230/147404711-10c319ef-a90a-4fd8-96be-4b71b0931d05.jpg)
> 
> Lu bikin project kok g ngajak2 sih njir
> 
> > @Felix-403
> > @Lingz-ui

Dah tau duo bukan squad 
Lu bikin sama Arya aja 

## (^～^)

**Comment by Len-cmd** [comment]
> > ![IMG_20211226_164853_762](https://user-images.githubusercontent.com/84387230/147404711-10c319ef-a90a-4fd8-96be-4b71b0931d05.jpg)
> > Lu bikin project kok g ngajak2 sih njir
> > > @Felix-403
> > > @Lingz-ui
> 
> Dah tau duo bukan squad Lu bikin sama Arya aja
> 
> ## (^～^)

### Ling-kun baka ＞////＜
